spring:
  application:
    name: products-ws
  devtools:
    restart:
      enabled: true
  # Does not serialize properties with null values
  jackson:
    default-property-inclusion: non_null

  mvc:
    pathmatch:
      # To resolve issue caused by Spring Fox 3.0.0 not supporting new
      # PathPattern Based Path Matching Strategy for Spring MVC which is now the new default from spring-boot 2.6.0.
      matching-strategy: ant_path_matcher

server:
  port: ${PORT:8015}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_PROTOCOL:http}://${EUREKA_HOST:localhost}:${EUREKA_PORT:8010}/eureka
  instance:
    prefer-ip-address: true
    homePageUrl: ${app.hostname}/
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.keyValue}}

app:
  hostname: ${EXTERNAL_PROTOCOL:http}://${EXTERNAL_HOST:localhost}:${EXTERNAL_PORT:8015}
  frontend: ${FRONTEND_PROTOCOL:http}://${FRONTEND_HOST:localhost}:${FRONTEND_PORT:4200}
